service: index-assignment
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
